Minihomework2 (Grishin Daniil)
itmogamedev/cpp2024 pull request #133
Opened 2024-10-03 19:54 UTC by FadriusGC

Сделал вторую минидомашку

2024-12-15 18:56 UTC, k-kondyukov approved these changes

2024-12-15 18:57 UTC, k-kondyukov commented
Крч у вас конфликты, можете обновить локально репо и заново залить код или решить конфликты. Пока не исправите, не смогу зачесть

2024-12-15 18:57 UTC, k-kondyukov requested changes
Исправить конфликт

2024-12-16 17:15 UTC, FadriusGC commented
Попытался исправить

2025-01-05 14:32 UTC, closed without merging