Mini homework2
itmogamedev/cpp2024 pull request #135
Opened 2024-10-04 06:46 UTC by Observer556

Я завершил выполнение минидомашки №2. Всё как вы просили: нормальные названия, защита от дурака (хоть какая-то), полностью выполненно задание. Только .cpp файлы. Надеюсь вы оцените!

2024-12-15 18:58 UTC, k-kondyukov approved these changes
пожалуйста, поместите ваш код в папку sem1 еще

2024-12-15 18:58 UTC, k-kondyukov requested changes
Требую переместить код

2024-12-16 11:45 UTC, Observer556 commented
Переместил папку

2024-12-25 05:48 UTC, k-kondyukov approved these changes

2024-12-25 05:48 UTC, merged