MiniHomeWork2 - task1 Kamalova Julia
itmogamedev/cpp2024 pull request #186
Opened 2024-10-06 16:25 UTC by juuunnii

2024-10-06 22:28 UTC, juuunnii commented
У меня день рождения 7 октября, не будьте так жестоки, помилуйте, честно-честно!

2024-12-18 21:07 UTC, k-kondyukov requested changes
Требую исправлений!

2024-12-18 21:07 UTC, k-kondyukov commented on sem1/Kamalova Julia/MiniHomeWork2/task1.cpp
> +using namespace std;
С такой строкой не принимаю

2024-12-25 06:08 UTC, k-kondyukov approved these changes

2024-12-25 06:08 UTC, merged