ДЗ №1
itmogamedev/cpp2024 pull request #24
Opened 2024-09-17 20:38 UTC by hennncho

Камболов Х.С. J3100
khetagkambolov@gmail.com

2024-09-30 17:41 UTC, hennncho commented
Мини дз № 2
Камболов Х.С. J3100
[khetagkambolov@gmail.com](mailto:khetagkambolov@gmail.com)

2024-12-14 23:16 UTC, k-kondyukov requested changes
Требую исправлений

2024-12-14 23:16 UTC, k-kondyukov commented on sem1/KhetagKambolov/MiniHomeWork1/Task1.cpp
> +
Почему main пустой?

2024-12-14 23:16 UTC, k-kondyukov commented on sem1/KhetagKambolov/MiniHomeWork1/Task2.cpp
> +
и тут?

2025-01-11 15:55 UTC, merged