Домашняя работа за 15 сентября
itmogamedev/cpp2024 pull request #39
Opened 2024-09-21 10:11 UTC by TyazhelovIlyaOlegovich

2024-12-14 23:59 UTC, k-kondyukov requested changes
Требую исправлений!

2024-12-14 23:59 UTC, k-kondyukov commented on sem1/TyazhelovIlyaOlegovich/MiniHomeWork1/.vscode/c_cpp_properties.json
> +    "configurations": [
Файлы json меня не интересуют. Нужно только исходники!

2024-12-15 10:22 UTC, TyazhelovIlyaOlegovich commented on sem1/TyazhelovIlyaOlegovich/MiniHomeWork1/.vscode/c_cpp_properties.json
> +    "configurations": [
Удалил файлы json. Правда там остались файлы, в которых пишется "Binary file not shown.", но я не могу их удалить. Возможно они как-то связаны с основными файлами, так как я первые 2 мини домашки делал на компьютере в коворкинге Ломоносова

2024-12-16 00:10 UTC, TyazhelovIlyaOlegovich commented
Исправил, оставив только файлы с кодом воскресенье, 15 декабря 2024г., 03:00 +03:00 от Kostya Kondyukov  ***@***.*** :

>@k-kondyukov requested changes on this pull request.
>Требую исправлений!
>----------------------------------------------------------------------
>In  sem1/TyazhelovIlyaOlegovich/MiniHomeWork1/.vscode/c_cpp_properties.json :
> @@ -0,0 +1,20 @@
>+{
>+    "configurations": [
>
>Файлы json меня не интересуют. Нужно только исходники!
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2025-01-05 14:08 UTC, k-kondyukov approved these changes

2025-01-05 14:08 UTC, merged