Сделал домашнюю работу из 4 заданий. Синицын Елисей 467472
itmogamedev/cpp2024 pull request #50
Opened 2024-09-22 14:18 UTC by Nionchik

2024-12-15 00:09 UTC, k-kondyukov requested changes
Требую исправлений!

2024-12-15 00:09 UTC, k-kondyukov commented on sem1/EliseySin/mini DZ/miniDZ_2.cpp
> +    std::cin >> chislo;
С транслитом в именах переменных и функций домашки не принимаю!

2024-12-19 18:19 UTC, Nionchik commented on sem1/EliseySin/mini DZ/miniDZ_2.cpp
> +    std::cin >> chislo;
исправил транслит в мини дзшках

2025-01-05 14:19 UTC, k-kondyukov requested changes

2025-01-05 14:19 UTC, k-kondyukov commented on sem1/EliseySin/DZ_1/dz_1.cpp
> +    int svk = sk*sk;
это не функция

2025-01-05 18:14 UTC, k-kondyukov approved these changes

2025-01-05 18:14 UTC, merged